services:
  mysql-db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 0120
      MYSQL_DATABASE: kimchijjim-db
      MYSQL_USER: kimchijjim-user
      MYSQL_PASSWORD: kimchijjim1!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: